[package]
name = "hdf5file"
version = "0.1.0"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1"
byteorder = "1"
itertools = "0.8"
trackable = "0.2"

[dev-dependencies]
structopt = "0.2"
